export const DISCOVER_SET_PAGINATION = 'DISCOVER_SET_PAGINATION';
export const DISCOVER_SET_OPTIONS = 'DISCOVER_SET_OPTIONS';

export const DISCOVER_REQUEST_DATA_IS_PENDING = 'DISCOVER_REQUEST_DATA_IS_PENDING';
export const DISCOVER_REQUEST_DATA_SUCCESS = 'DISCOVER_REQUEST_DATA_SUCCESS';
export const DISCOVER_REQUEST_DATA_FAILURE = 'DISCOVER_REQUEST_DATA_FAILURE';
