export const MOVIE_REQUEST_DETAILS_IS_PENDING = 'MOVIE_REQUEST_DETAILS_IS_PENDING';
export const MOVIE_REQUEST_DETAILS_SUCCESS = 'MOVIE_REQUEST_DETAILS_SUCCESS';
export const MOVIE_REQUEST_DETAILS_FAILURE = 'MOVIE_REQUEST_DETAILS_FAILURE';

export const MOVIE_REQUEST_CREDITS_IS_PENDING = 'MOVIE_REQUEST_CREDITS_IS_PENDING';
export const MOVIE_REQUEST_CREDITS_SUCCESS = 'MOVIE_REQUEST_CREDITS_SUCCESS';
export const MOVIE_REQUEST_CREDITS_FAILURE = 'MOVIE_REQUEST_CREDITS_FAILURE';
